# Generated by Django 3.1.6 on 2021-02-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20210218_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default=0, upload_to='media/'),
        ),
    ]
