# Generated by Django 3.1.6 on 2021-02-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20210224_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_contacto', models.IntegerField(choices=[('0', 'Contacto'), ('1', 'Reclamo'), ('2', 'Problema al momento de comprar'), ('3', 'Sugerencias'), ('4', 'Felicitaciones')])),
                ('mensaje', models.CharField(max_length=200)),
                ('avisos', models.BooleanField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='monto_boleta',
        ),
    ]
