# Generated by Django 3.1.6 on 2021-03-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20210225_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_contacto',
            field=models.CharField(choices=[('C', 'Contacto'), ('R', 'Reclamo'), ('P', 'Problema al momento de comprar'), ('S', 'Sugerencias'), ('F', 'Felicitaciones')], max_length=1),
        ),
    ]
