# Generated by Django 3.1.6 on 2021-03-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20210302_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['id'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'ordering': ['id'], 'verbose_name': 'DetalleVenta', 'verbose_name_plural': 'DetalleVentas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['id'], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['id'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='detalleVenta',
        ),
        migrations.AlterModelTable(
            name='sucursal',
            table='sucursal',
        ),
        migrations.AlterModelTable(
            name='venta',
            table='venta',
        ),
    ]
