# Generated by Django 3.1.6 on 2021-03-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20210307_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['id'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelTable(
            name='contacto',
            table='contacto',
        ),
    ]
