# Generated by Django 3.1.6 on 2021-03-19 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_auto_20210307_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
    ]
